### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sjoller** [xorgate/TabSwitcherExtreme#9]
I've set up a few tabs, but there seems to be missing several files from the results.

As an example, I have a "Lang" folder containing 3 language files, but it'll only display 2 of them. As they're named similarly, the regex should find all of those.

**Comment by xorgate** [comment]
Please realise that the plugin only shows files that are currently open in the IDE. This means that there is an 'editor tab' for this file somewhere.

Files can exist in folders and not show up in the plugin, just like IDEAs own file switcher. Otherwise there might be thousands.

If you're certain the file is open, make sure that there is not another column with a regex that will find the file first. A regex for .png and one for /bitmaps/ might both match a certain file, but only the first one will show it in the list. Otherwise it will show up in the auto-generated column of 'All' (if memory serves me correctly).

Hope this helps

**Comment by sjoller** [comment]
Thanks, I missed that it's only showing open files. That fully explains my issue, so I'll close this.
